workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

stages: [generate, build]

generate:
  stage: generate
  image:
    name: ghcr.io/vaskozl/melange:0.50.4@sha256:f25c622d9258a171971d5d3bee8a867643828a31e7ad39a56b02cd8d99432ac4
    entrypoint: [""]
  script:
    - .gitlab/gen-dag.sh > generated-pipeline.yml
  artifacts:
    paths: [generated-pipeline.yml]

build:
  stage: build
  needs: [generate]
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: generate
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        IS_MAIN: "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        IS_MAIN: "false"
