workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

stages: [generate, build]

generate:
  stage: generate
  image:
    name: ghcr.io/vaskozl/melange:0.50.5@sha256:d374bbc6b1943485615ad9d9fd0821962bff439d4e6b01f11a532ec8ac4d0721
    entrypoint: [""]
  script:
    - .gitlab/gen-dag.sh > generated-pipeline.yml
  artifacts:
    paths: [generated-pipeline.yml]

build:
  stage: build
  needs: [generate]
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: generate
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        IS_MAIN: "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        IS_MAIN: "false"
