stages: [generate, build]

generate:
  stage: generate
  image:
    name: ghcr.io/vaskozl/melange:0.50.4@sha256:5213c379264b4e2b360451b42d531f8e8d9be19797b935afe7bc5ac12e2b3bb8
    entrypoint: [""]
  script:
    - .gitlab/gen-dag.sh > generated-pipeline.yml
  artifacts:
    paths: [generated-pipeline.yml]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build:
  stage: build
  needs: [generate]
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: generate
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
