# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: asahi-fwextract
  version: "0.8.1"
  epoch: 0
  description: Asahi Linux firmware extractor
  copyright:
    - license: MIT
  target-architecture:
    - aarch64
  dependencies:
    runtime:
      - lzfse
      - python-${{vars.python-version}}-base
vars:
  python-version: "3.13"
environment:
  contents:
    packages:
      - busybox
      - py3-supported-build
      - py3-supported-installer
      - py3-supported-setuptools
      - py3-supported-wheel
      - python-${{vars.python-version}}
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/AsahiLinux/asahi-installer
      tag: v${{package.version}}
  - name: build wheel
    runs: |
      set -eu
      python${{vars.python-version}} -m build --wheel --no-isolation
  - name: install
    runs: |
      set -eu
      python${{vars.python-version}} -m installer --destdir="${{targets.destdir}}" dist/*.whl
      install -Dm644 LICENSE "${{targets.destdir}}/usr/share/licenses/${{package.name}}/LICENSE"
test:
  pipeline:
    - uses: test/help-check
      with:
        bins: |
          asahi-fwextract
    - name: entry point import
      runs: |
        set -eu
        python${{vars.python-version}} -c "from asahi_firmware.update import main; assert callable(main)"
update:
  enabled: true
  git: {}
