package:
  name: bootc
  version: 1.11.0
  epoch: 0
  description: Boot and upgrade via container images
  copyright:
    - license: Apache-2.0-only
  dependencies:
    runtime:
      - fstrim
      - ostree
      - composefs
      - mount
      - umount
      - util-linux-misc
environment:
  contents:
    packages:
      - automake
      - busybox
      - build-base
      - ostree-dev
      - cargo-auditable
      - rust
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bootc-dev/bootc.git
      tag: v${{package.version}}
  - runs: |
      make bin install-all install-initramfs-dracut \
        STORAGE_RELATIVE_PATH=/sysroot/ostree/bootc/storage \
        DESTDIR="${{targets.contextdir}}" \
        V=1
  - runs: |
      mkdir -p ${{ targets.destdir }}/usr/lib/ostree/
      install -Dm644 ./prepare-root.conf ${{ targets.destdir }}/usr/lib/ostree/prepare-root.conf
      install -Dm644 ./bootc-base-dirs.conf ${{targets.destdir}}/usr/lib/tmpfiles.d/bootc-base-dirs.conf
  - uses: strip
subpackages:
  - name: bootc-doc
    pipeline:
      - uses: split/manpages
    description: bootc manpages
test:
  environment:
    contents:
      packages:
        - yq
  pipeline:
    - runs: |
        set -o pipefail
        bootc --version | grep -F -e "${{package.version}}"
        bootc status | yq .apiVersion | grep -F -e "org.containers.bootc/v1"
