package:
  name: dracut
  version: "108"
  epoch: 0
  description: Initramfs generator using udev
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later AND GPL-2.0-only
  dependencies:
    runtime:
      - coreutils
      - cpio
      - udev
environment:
  contents:
    packages:
      - bash
      - build-base
      - coreutils
      - kmod-dev
      - pkgconf-dev
      - rust
      - systemd-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dracut-ng/dracut-ng.git
      tag: ${{package.version}}
  - uses: autoconf/configure
    with:
      opts: |
        --sysconfdir=/etc \
        --prefix=/usr \
        --libdir=/usr/lib \
        --systemdsystemunitdir=/usr/lib/systemd \
        --enable-dracut-cpio
  - uses: autoconf/make-install
    with:
      opts: |
        enable_documentation=no
  - runs: |
      mkdir -p ${{targets.destdir}}/etc/dracut.conf.d
      install -Dm644 ./fix-bootc.conf ${{targets.destdir}}/etc/dracut.conf.d/fix-bootc.conf
  - uses: strip
subpackages:
  - name: dracut-dev
    description: Headers and dev libraries from Dracut
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
test:
  pipeline:
    - runs: |
        set -o pipefail
        dracut --help | grep -F -e "Creates initial ramdisk images for preloading modules"
        dracut --version | grep -F -e "${{package.version}}"
        lsinitrd --help 2>&1 | grep -F -e "Usage: lsinitrd"
        dracut-catimages --help 2>&1 | grep -F -e "Creates initial ramdisk image by concatenating several images from the command"
