package:
  name: foot
  version: "1.25.0"
  epoch: 0
  description: Fast, lightweight and minimalistic Wayland terminal emulator
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - xkeyboard-config
environment:
  contents:
    packages:
      - build-base
      - cage
      - ttf-dejavu
      - fcft-dev
      - fontconfig-dev
      - freetype-dev
      - libxkbcommon-dev
      - meson
      - ncurses
      - pixman-dev
      - scdoc
      - tllist-dev
      - utf8proc-dev
      - wayland-dev
      - wayland-protocols
pipeline:
  - uses: git-checkout
    with:
      repository: https://codeberg.org/dnkl/foot.git
      tag: ${{package.version}}
  - runs: |
      ln -s /usr/bin/scdoc /usr/local/bin/scdoc
  - uses: meson/configure
  - uses: meson/compile
  - uses: meson/install
  - uses: strip
subpackages:
  - name: "${{package.name}}-terminfo"
    description: "foot terminal descriptions"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/terminfo "${{targets.subpkgdir}}"/usr/share
  - name: "${{package.name}}-themes"
    description: "foot terminal themes"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/foot
          mv "${{targets.destdir}}"/usr/share/foot/themes "${{targets.subpkgdir}}"/usr/share/foot/
  - name: "${{package.name}}-dbg"
    pipeline:
      - uses: split/debug
  - name: "${{package.name}}-doc"
    pipeline:
      - uses: split/alldocs
    description: foot manpages
  - name: "${{package.name}}-bash-completion"
    description: "bash completion for bspc"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/bash-completion/completions
          mv ${{targets.destdir}}/usr/share/bash-completion/completions ${{targets.subpkgdir}}/usr/share/bash-completion/completions
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
  - name: "${{package.name}}-zsh-completion"
    description: "foot completions"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/zsh
          mv ${{targets.destdir}}/usr/share/zsh/site-functions ${{targets.subpkgdir}}/usr/share/zsh/site-functions
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
  - name: "${{package.name}}-fish-completion"
    description: "foot completions"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/fish
          mv ${{targets.destdir}}/usr/share/fish/vendor_completions.d ${{targets.subpkgdir}}/usr/share/fish/vendor_completions.d
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
test:
  pipeline:
    - runs: |
        foot --help
