package:
  name: grim
  version: "1.4.0"
  epoch: 0
  description: Screenshot utility for Wayland compositors
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - build-base
      - libjpeg-turbo-dev
      - libpng-dev
      - meson
      - pixman-dev
      - scdoc
      - wayland-dev
      - wayland-protocols
      - wayland-protocols-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/emersion/grim
      tag: v${{package.version}}
  - uses: meson/configure
    with:
      opts: -Djpeg=enabled
  - uses: meson/compile
  - uses: meson/install
  - uses: strip
subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: grim manpages
    test:
      pipeline:
        - uses: test/docs
  - name: ${{package.name}}-dbg
    pipeline:
      - uses: split/debug
    description: grim debug symbols
test:
  pipeline:
    - uses: test/help-check
      with:
        bins: |
          grim
