# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: kernel
  version: 6.17.8
  epoch: 1
  description: The Linux kernel
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - zstd
environment:
  contents:
    packages:
      - binutils-dev
      - bison
      - build-base
      - busybox
      - diffutils
      - elfutils
      - elfutils-dev
      - findutils
      - openssl-dev
      - flex
      - perl
      - rsync
      - gawk
      - gnutar
      - kmod
      - libelf
      - llvm
      - openssl
      - xz
      - zstd
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gregkh/linux
      tag: v${{package.version}}
  - runs: mv config-${{build.arch}}* .config
  - uses: autoconf/make
    with:
      opts: prepare
  - uses: autoconf/make
    with:
      opts: modules_prepare
  - uses: autoconf/make
  - uses: autoconf/make
    with:
      opts: headers_install INSTALL_HDR_PATH=${{targets.destdir}}/usr
  - runs: |
      install -Dpm0644 ./arch/${{build.arch}}/boot/bzImage "${{targets.destdir}}/usr/lib/modules/${{package.version}}/vmlinuz"
      install -Dpm0644 .config ${{targets.destdir}}/usr/lib/modules/${{package.version}}/config
      install -Dpm0644 -t "${{targets.destdir}}/usr/lib/modules/${{package.version}}/" ./System.map
subpackages:
  - name: kernel-modules
    description: Kernel modules
    dependencies:
      runtime:
        - xz
    pipeline:
      - uses: autoconf/make
        with:
          opts: modules_install INSTALL_MOD_PATH=${{targets.subpkgdir}}/usr
      - runs: |
          echo "Compressing kernel modules with xz..."
          find ${{targets.subpkgdir}}/usr/lib/modules/ -type f -name '*.ko' -print0 | xargs -0 -n1 -P$(nproc) xz -T1 --check=crc32 --lzma2=dict=1MiB
    test:
      pipeline:
        - runs: |
            stat "${{targets.subpkgdir}}/usr/lib/modules/${{package.version}}" | grep -F -e "0755"
            test -d "${{targets.subpkgdir}}/usr/lib/modules/${{package.version}}"
            if find "${{targets.subpkgdir}}/usr/lib/modules/${{package.version}}" -type f -name '*.ko' | grep -q .; then
              print "%s" "Found uncompressed kernel object files" >&2
              exit 1
            fi
  - name: kernel-dev
    description: Kernel headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
