# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: kernel-initramfs
  version: 7.0.3
  epoch: 2 # derive module dir from kernel package at build time
  description: The Linux kernel initramfs
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - kernel=${{package.version}}
      - zstd
environment:
  contents:
    packages:
      - attr
      - bash
      - binutils-dev
      - bootc
      - busybox
      - build-base
      - dracut
      - findutils
      - kernel=${{package.version}}
      - kmod
      - posix-libc-utils
      - wolfi-baselayout
      - zstd
      # For modules
      - blkid
      - btrfs-progs
      - cryptsetup
      - device-mapper
      - losetup
      - lvm2
      - mount
      - openssl
      - systemd
      - umount
      - util-linux
      - util-linux-login
pipeline:
  - runs: |
      KMOD_DIR=$(ls /lib/modules | head -1)
      mkdir -p /var/tmp ${{targets.destdir}}/usr/lib/modules/$KMOD_DIR
      ls -al /lib/modules
      depmod "$KMOD_DIR"
      dracut --force --verbose --kernel-cmdline "SYSTEMD_SULOGIN_FORCE=1" \
        ${{targets.destdir}}/usr/lib/modules/$KMOD_DIR/initramfs.img
  - runs: |
      KMOD_DIR=$(ls /lib/modules | head -1)
      ls -la ${{targets.destdir}}/usr/lib/modules/$KMOD_DIR/
