# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: kernel
  version: 6.17.8
  epoch: 0
  description: Repackaged Alpine linux-stable kernel
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - kmod
      - gzip

environment:
  contents:
    packages:
      - wolfi-base
      - apk-tools
      - busybox
      - wget
      - gzip

pipeline:
  # Fetch Alpine linux-lts package
  - runs: |
      set -eux
      mkdir alpinepkg
      cd alpinepkg
      branch="edge"
      repo="community"
      variant="linux-stable"

      # Adjust repo & arch as needed
      wget "https://dl-cdn.alpinelinux.org/alpine/${branch}/${repo}/${{build.arch}}/${variant}-${{package.full-version}}.apk"

      # Extract fetched APK
      for f in *.apk; do
        tar -xzf "$f"
      done

  # Install payload into destdir
  - runs: |
      out="${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}}-stable"
      install -d "${out}"
      cp -a "alpinepkg/lib/modules/${{package.version}}-${{package.epoch}}-stable/." "${out}/"
      cp -a "alpinepkg/boot/vmlinuz-stable" "${out}/vmlinuz"
      cp -a "alpinepkg/boot/config-${{package.version}}-${{package.epoch}}-stable" "${out}/config"
      cp -a "alpinepkg/boot/System.map-${{package.version}}-${{package.epoch}}-stable" "${out}/System.map"
