# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json

package:
  name: kernel-rpi-initramfs
  version: 6.17.8
  epoch: 0
  description: The Linux kernel initramfs
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - kernel-rpi
      - zstd

environment:
  contents:
    packages:
      - busybox
      - build-base
      - bash
      - binutils-dev
      - wolfi-baselayout
      - kernel
      - bootc
      - dracut
      - kmod
      - zstd
      - posix-libc-utils
      - attr
      - findutils
      # For modules
      - lvm2
      - cryptsetup
      - btrfs-progs
      - systemd
      - util-linux
      - device-mapper
      - openssl
      - util-linux-login
      - mount
      - umount
      - blkid
      - losetup


pipeline:
  - runs: |
      mkdir -p /var/tmp ${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-rpi
      ls -al /lib/modules
      depmod ${{package.version}}-${{package.epoch}}-rpi
      dracut --force --no-hostonly --reproducible --zstd --verbose \
        --kver ${{package.version}}-${{package.epoch}}-rpi --omit busybox \
        ${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-rpi/initramfs.img \
        --kernel-cmdline "SYSTEMD_SULOGIN_FORCE=1"

  - runs: |
      ls -la ${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-stable/
