# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: kernel-initramfs
  version: 6.18.5
  epoch: 0
  description: The Linux kernel initramfs
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - kernel
      - kernel-initramfs
      - zstd
environment:
  contents:
    packages:
      - busybox
      - build-base
      - bash
      - binutils-dev
      - wolfi-baselayout
      - kernel
      - bootc
      - dracut
      - kmod
      - zstd
      - posix-libc-utils
      - attr
      - findutils
      # For modules
      - lvm2
      - cryptsetup
      - btrfs-progs
      - systemd
      - util-linux
      - device-mapper
      - openssl
      - util-linux-login
      - mount
      - umount
      - blkid
      - losetup
pipeline:
  - runs: |
      mkdir -p /var/tmp ${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-stable
      ls -al /lib/modules
      depmod ${{package.version}}-${{package.epoch}}-stable
      dracut --force --verbose --kernel-cmdline "SYSTEMD_SULOGIN_FORCE=1" \
        ${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-stable/initramfs.img
  - runs: |
      ls -la ${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-stable/
