# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: kernel
  version: 6.18.5
  epoch: 0
  description: Repackaged Alpine linux-stable kernel
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:
      - kmod
      - gzip
    provides:
      - linux:${{package.version}}-${{package.epoch}}-stable

environment:
  contents:
    packages:
      - wolfi-base
      - apk-tools
      - busybox
      - wget
      - gzip

pipeline:
  # Fetch Alpine linux-lts package
  - runs: |
      set -eux
      mkdir alpinepkg
      cd alpinepkg
      branch="edge"
      repo="community"
      variant="linux-stable"

      # Adjust repo & arch as needed
      wget "https://dl-cdn.alpinelinux.org/alpine/${branch}/${repo}/${{build.arch}}/${variant}-${{package.full-version}}.apk"

      # Extract fetched APK
      for f in *.apk; do
        tar -xzf "$f"
      done

  - runs: |
      out="${{targets.destdir}}/usr/lib/modules/${{package.version}}-${{package.epoch}}-stable"

      # Copy module tree
      find "alpinepkg/lib/modules/${{package.version}}-${{package.epoch}}-stable" -type f \
        | while read -r f; do
            rel="${f#alpinepkg/lib/modules/${{package.version}}-${{package.epoch}}-stable/}"
            install -Dm0644 "$f" "$out/$rel"
          done

      # Kernel artifacts
      install -Dm0644 "alpinepkg/boot/vmlinuz-stable" \
        "$out/vmlinuz"
      install -Dm0644 "alpinepkg/boot/config-${{package.version}}-${{package.epoch}}-stable" \
        "$out/config"
      install -Dm0644 "alpinepkg/boot/System.map-${{package.version}}-${{package.epoch}}-stable" \
        "$out/System.map"
