package:
  name: libliftoff
  version: "0.5.0"
  epoch: 0
  description: Lightweight KMS plane library
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - build-base
      - meson
      - libdrm-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/emersion/libliftoff
      tag: v${{package.version}}
  - runs: |
      meson \
        --prefix=/usr \
        . output
  - uses: meson/compile
  - uses: meson/install
  - uses: strip
subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    description: ${{package.name}} manpages
