package:
  name: libva-intel-driver
  version: "2.4.1"
  epoch: 0
  description: VA-API user mode driver for Intel Gen4-Gen9 GPUs (i965)
  copyright:
    - license: MIT
  target-architecture:
    - x86_64
  dependencies:
    runtime:
      - libva
      - libdrm

environment:
  contents:
    packages:
      - build-base
      - libdrm-dev
      - libva-dev
      - meson
      - wayland-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/intel/intel-vaapi-driver
      tag: ${{package.version}}
  - uses: meson/configure
    with:
      opts: |
        -Dwith_x11=no
  - uses: meson/compile
  - uses: meson/install
  - uses: strip

subpackages:
  - name: "${{package.name}}-dev"
    pipeline:
      - uses: split/dev
    description: libva-intel-driver dev headers

test:
  pipeline:
    - runs: |
        stat /usr/lib/dri/i965_drv_video.so
