package:
  name: m1n1
  version: "1.6.0"
  epoch: 0
  description: Bootloader and experimentation playground for Apple Silicon
  copyright:
    - license: MIT
  target-architecture:
    - aarch64
environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - imagemagick
      - llvm
      - rust
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/AsahiLinux/m1n1
      tag: v${{package.version}}
      recurse-submodules: true
  - runs: |
      set -eu
      make ARCH= BUILDSTD=1
      mkdir -p ${{targets.destdir}}/usr/share/m1n1
      install -m644 build/m1n1.bin   ${{targets.destdir}}/usr/share/m1n1/
      install -m644 build/m1n1.macho ${{targets.destdir}}/usr/share/m1n1/
test:
  pipeline:
    - runs: |
        set -eu
        test -f /usr/share/m1n1/m1n1.bin
        test -f /usr/share/m1n1/m1n1.macho
        head -c4 /usr/share/m1n1/m1n1.macho | od -An -tx1 | grep -E 'cf fa ed fe|ca fe ba be|fe ed fa cf|be ba fe ca'
update:
  enabled: true
  github:
    identifier: AsahiLinux/m1n1
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
