package:
  name: mako
  version: "1.11.0"
  epoch: 0
  description: A lightweight notification daemon for Wayland
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - build-base
      - cairo-dev
      - gdk-pixbuf-dev
      - json-c-dev
      - libxkbcommon-dev
      - meson
      - pango-dev
      - scdoc
      - systemd-dev
      - wayland-dev
      - wayland-protocols
      - wayland-protocols-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/emersion/mako
      tag: v${{package.version}}
  - runs: |
      ln -s /usr/bin/scdoc /usr/local/bin/scdoc
  - uses: meson/configure
    with:
      opts: |
        -Dsd-bus-provider=libsystemd \
        -Dicons=enabled
  - uses: meson/compile
  - uses: meson/install
  - uses: strip
subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: mako manpages
    test:
      pipeline:
        - uses: test/docs
  - name: ${{package.name}}-dbg
    pipeline:
      - uses: split/debug
    description: mako debug symbols
test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/help-check
      with:
        bins: |
          mako
          makoctl
