# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: moarvm
  version: "2026.02"
  epoch: 0
  description: VM with adaptive optimization and JIT compilation
  copyright:
    - license: Artistic-2.0
  dependencies:
    runtime:
      - libffi
      - libuv
      - mimalloc
      - zstd
  resources:
    cpu: "4"
    memory: 8Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libffi-dev
      - libuv-dev
      - mimalloc-dev
      - perl
      - perl-utils
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/MoarVM/MoarVM
      tag: ${{package.version}}

  - runs: |
      # Configure moarvm
      unset CPPFLAGS CFLAGS
      perl Configure.pl \
        --prefix=/usr \
        --has-libffi \
        --has-libuv \
        --has-mimalloc \
        --debug \
        --cc="$CC"

  - runs: |
      # Build
      make

  - runs: |
      # Install
      make DESTDIR="${{targets.destdir}}" install

  - uses: strip

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - name: Verify moarvm binary exists
      runs: |
        stat /usr/bin/moar
    - name: Verify moarvm is executable
      runs: |
        test -x /usr/bin/moar
