package:
  name: nori-user
  version: "2"
  epoch: 0
  description: nori setup user
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - busybox
pipeline:
  - runs: |
      cp -a vendor/. "${{targets.destdir}}"/
      find "${{targets.destdir}}" -type f -exec chmod 644 {} +
