package:
  name: nori-user
  version: "2"
  epoch: 1 # add test section
  description: nori setup user
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - busybox
pipeline:
  - runs: |
      cp -a vendor/. "${{targets.destdir}}"/
      find "${{targets.destdir}}" -type f -exec chmod 644 {} +
test:
  pipeline:
    - runs: |
        set -eu
        stat /etc/sudoers.d/nori-user
        stat /etc/ssh/sshd_config.d/nori-user.conf
        stat /usr/lib/sysusers.d/nori-user.conf
        stat /usr/lib/tmpfiles.d/nori-user.conf
        stat /usr/lib/systemd/system/systemd-sysusers.service.d/nori-user.conf
