package:
  name: ostree
  version: "2025.7"
  epoch: 0
  description: "Operating system and container binary deployment and upgrades"
  copyright:
    - license: GPL-2.0-only
environment:
  contents:
    packages:
      - bison
      - build-base
      - composefs-dev
      - curl-dev
      - e2fsprogs-dev
      - fuse3-dev
      - glib-dev
      - gpgme-dev
      - libarchive-dev
      - libselinux-dev
      - libtool
      - pkgconf-dev
      - systemd-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ostreedev/ostree.git
      tag: v${{package.version}}
  - runs: env NOCONFIGURE=1 ./autogen.sh
  - uses: autoconf/configure
    with:
      opts: |
        --disable-silent-rules \
        --enable-gtk-doc \
        --with-selinux \
        --with-curl \
        --with-openssl \
        --without-soup \
        --with-composefs \
        --with-dracut=yesbutnoconf
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: ostree-dev
    description: Headers and dev libraries from ostree
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
test:
  pipeline:
    - runs: |
        set -o pipefail
        ostree --help | grep -F -e "Commands for managing a host system booted with ostree"
        ostree --version | grep -F -e "${{package.version}}"
    - name: Ensure expected modules are installed
      runs: |
        set -o pipefail
        MODULES_OUTPUT=$(mktemp)
        ostree --version 2>&1 | tee "${MODULES_OUTPUT}"
        grep_file() {
          grep -F -e $@ "${MODULES_OUTPUT}"
        }
        grep_file "inode64"
        grep_file "initial-var"
        grep_file "libcurl"
        # TODO: enable this one libsoup is packaged
        # grep_file "libsoup3"
        grep_file "gpgme"
        grep_file "composefs"
        grep_file "ex-fsverity"
        grep_file "libarchive"
        grep_file "selinux"
        grep_file "openssl"
        grep_file "sign-ed25519"
        grep_file "sign-spki"
        grep_file "libmount"
        grep_file "systemd"
        grep_file "release"
        grep_file "p2p"
update:
  enabled: true
  github:
    identifier: ostreedev/ostree
    strip-prefix: v
