# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/refs/heads/main/pkg/config/schema.json
package:
  name: tsidp
  version: 0.0.12
  epoch: 1 # add go-package, drop build-base, improve tests
  description: A simple OIDC / OAuth Identity Provider (IdP) server for your tailnet.
  copyright:
    - license: BSD-3-Clause
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tailscale/tsidp
      tag: v${{package.version}}
  - uses: go/build
    with:
      go-package: go-1.26
      packages: ./
      output: tsidp-server
  - uses: strip
test:
  pipeline:
    - uses: test/help-check
      with:
        bins: |
          tsidp-server
