package:
  name: wayland-protocols
  version: "1.48"
  epoch: 0
  description: Wayland protocol extensions
  copyright:
    - license: MIT
environment:
  contents:
    packages:
      - build-base
      - meson
      - python3
      - samurai
      - wayland-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/wayland/wayland-protocols
      tag: ${{package.version}}
  - uses: meson/configure
  - uses: meson/compile
  - uses: meson/install
  - uses: strip
subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    description: ${{package.name}} headers and pkg-config files
    test:
      pipeline:
        - uses: test/pkgconf
test:
  pipeline:
    - runs: |
        set -eu
        stat /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml
