package:
  name: xdg-desktop-portal
  version: 1.20.4
  epoch: 0
  description: Desktop integration portal for sandboxed applications
  copyright:
    - license: LGPL-2.1-or-later
  dependencies:
    runtime:
      - bubblewrap
      - dbus
environment:
  contents:
    packages:
      - build-base
      - bubblewrap
      - dbus-dev
      - fuse3-dev
      - gdk-pixbuf-dev
      - gettext-dev
      - glib-dev
      - gst-plugins-base-dev
      - json-glib-dev
      - meson
      - pipewire-dev
      - pkgconf-dev
      - python3
      - systemd-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flatpak/xdg-desktop-portal
      tag: ${{package.version}}
  - uses: meson/configure
    with:
      opts: |
        --wrap-mode=default \
        -Dsystemd=enabled \
        -Ddocumentation=disabled \
        -Dman-pages=disabled \
        -Dtests=disabled \
        -Dinstalled-tests=false \
        -Dflatpak-interfaces=disabled \
        -Dgeoclue=disabled \
        -Dgudev=disabled \
        -Dsandboxed-image-validation=enabled \
        -Dsandboxed-sound-validation=enabled
  - uses: meson/compile
  - uses: meson/install
  - uses: strip
subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development files (D-Bus interfaces, pkg-config)
    pipeline:
      - uses: split/dev
    test:
      environment:
        contents:
          packages:
            - pkgconf
      pipeline:
        - runs: pkg-config --exists xdg-desktop-portal
test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        set -eu
        /usr/libexec/xdg-desktop-portal --version
        stat /usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service
