#!/bin/sh
# Emit a GitLab child pipeline that builds every *.yaml package in this repo,
# with `needs:` set so dependent packages wait for their dependencies.
#
# The graph is derived purely from melange yaml introspection. For each yaml
# we union build-time deps (environment.contents.packages) and runtime deps
# (package.dependencies.runtime), strip version constraints, and resolve each
# remaining name against a map of locally-provided packages (package name +
# subpackage names). Cross-yaml deps become `needs:` edges; everything else is
# fetched from the published apk repository at build time.

set -eu

cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Per-yaml row: <base>|<provided-csv>|<target-arches-csv>|<deps-csv>
# where <provided> = package name + subpackage names, and <deps> = build deps
# concatenated with runtime deps (constraints stripped later).
QUERY='{{ .Package.Name }}{{ range .Subpackages }},{{ .Name }}{{ end }}|{{ range $i,$a := .Package.TargetArchitecture }}{{ if $i }},{{ end }}{{ $a }}{{ end }}|{{ range $i,$d := .Environment.Contents.Packages }}{{ if $i }},{{ end }}{{ $d }}{{ end }}{{ range .Package.Dependencies.Runtime }},{{ . }}{{ end }}'

for y in *.yaml; do
    printf '%s|%s\n' "${y%.yaml}" "$(melange query "$y" "$QUERY")"
done >"$WORK/rows"

# Provider map (sorted): "<provided-name> <yaml-base>"
awk -F'|' '
    { n = split($2, names, ",")
      for (i = 1; i <= n; i++) if (names[i] != "") print names[i], $1 }
' "$WORK/rows" | sort -u >"$WORK/providers"

# Supported (base, arch) pairs — empty target-architecture means "all".
awk -F'|' '
    { split($3, a, ",")
      has_amd64 = (a[1] == "")
      has_arm64 = (a[1] == "")
      for (i in a) {
          if (a[i] == "x86_64")  has_amd64 = 1
          if (a[i] == "aarch64") has_arm64 = 1
      }
      if (has_amd64) print $1, "amd64"
      if (has_arm64) print $1, "arm64" }
' "$WORK/rows" | sort -u >"$WORK/supports"

arch_supported() { grep -qxF "$1 $2" "$WORK/supports"; }

# Resolve a yaml's deps to other local yamls it depends on.
# All lookups happen in one awk pass against $WORK/providers (busybox lacks `join`).
resolve_deps() {
    awk -v self="$1" -v deps="$2" '
        { p[$1] = p[$1] " " $2 }
        END {
            n = split(deps, d, ",")
            for (i = 1; i <= n; i++) {
                name = d[i]
                sub(/[~=<>!].*/, "", name)
                if (name == "" || !(name in p)) continue
                m = split(p[name], a, " ")
                for (j = 1; j <= m; j++)
                    if (a[j] != "" && a[j] != self) print a[j]
            }
        }
    ' "$WORK/providers" | sort -u
}

cat <<'YAML'
# Auto-generated by .gitlab/gen-dag.sh — do not edit.
stages: [build]

.build:
  stage: build
  image:
    name: ghcr.io/vaskozl/melange:0.50.4@sha256:5213c379264b4e2b360451b42d531f8e8d9be19797b935afe7bc5ac12e2b3bb8
    entrypoint: [""]
  before_script:
    - echo "${MELANGE_RSA}" > melange.rsa
  variables:
    OUT_DIR: /apks
    MELANGE_FLAGS: >-
      --workspace-dir=$CI_PROJECT_DIR
      --arch=$ARCH
      --runner=bubblewrap
      --cache-dir=/apks/melange-cache
      --apk-cache-dir=/apks/apks-cache
      --repository-append=https://apks.sko.ai,https://packages.wolfi.dev/os
      --keyring-append=melange.rsa.pub,https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      --pipeline-dir=./pipelines
      --env-file=common.env
  retry: 2
  script:
    - melange build "$PKG" $MELANGE_FLAGS --source-dir="${PKG%.yaml}" --out-dir="$OUT_DIR" --signing-key=melange.rsa

noop:
  stage: build
  image: busybox
  script: ["true"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

YAML

while IFS='|' read -r base _ _ deps; do
    local_deps=$(resolve_deps "$base" "$deps")

    for arch in amd64 arm64; do
        arch_supported "$base" "$arch" || continue

        cat <<YAML
$base-$arch:
  extends: .build
  tags: [$arch]
  variables:
    PKG: $base.yaml
    ARCH: $arch
  rules:
    - if: \$CI_COMMIT_BRANCH == "main"
      changes:
        - $base.yaml
        - $base/**/*
    - when: never
YAML

        needs_header=
        for dep in $local_deps; do
            arch_supported "$dep" "$arch" || continue
            [ -z "$needs_header" ] && { printf '  needs:\n'; needs_header=1; }
            printf '    - {job: %s-%s, optional: true}\n' "$dep" "$arch"
        done
        echo
    done
done <"$WORK/rows"
