#!/bin/sh
# Emit a GitLab child pipeline that builds every *.yaml package in this repo,
# with `needs:` set so dependent packages wait for their dependencies.
#
# The graph is derived purely from melange yaml introspection. For each yaml
# we union build-time deps (environment.contents.packages) and runtime deps
# (package.dependencies.runtime), strip version constraints, and resolve each
# remaining name against a map of locally-provided packages (package name +
# subpackage names). Cross-yaml deps become `needs:` edges; everything else is
# fetched from the published apk repository at build time.

set -eu

cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Per-yaml row: <base>|<provided-csv>|<target-arches-csv>|<deps-csv>
# where <provided> = package name + subpackage names, and <deps> = build deps
# concatenated with runtime deps (constraints stripped later).
QUERY='{{ .Package.Name }}{{ range .Subpackages }},{{ .Name }}{{ end }}|{{ range $i,$a := .Package.TargetArchitecture }}{{ if $i }},{{ end }}{{ $a }}{{ end }}|{{ range $i,$d := .Environment.Contents.Packages }}{{ if $i }},{{ end }}{{ $d }}{{ end }}{{ range .Package.Dependencies.Runtime }},{{ . }}{{ end }}'

for y in *.yaml; do
    printf '%s|%s\n' "${y%.yaml}" "$(melange query "$y" "$QUERY")"
done >"$WORK/rows"

# Provider map (sorted): "<provided-name> <yaml-base>"
awk -F'|' '
    { n = split($2, names, ",")
      for (i = 1; i <= n; i++) if (names[i] != "") print names[i], $1 }
' "$WORK/rows" | sort -u >"$WORK/providers"

# Supported (base, arch) pairs — empty target-architecture means "all".
awk -F'|' '
    { split($3, a, ",")
      has_amd64 = (a[1] == "")
      has_arm64 = (a[1] == "")
      for (i in a) {
          if (a[i] == "x86_64")  has_amd64 = 1
          if (a[i] == "aarch64") has_arm64 = 1
      }
      if (has_amd64) print $1, "amd64"
      if (has_arm64) print $1, "arm64" }
' "$WORK/rows" | sort -u >"$WORK/supports"

arch_supported() { grep -qxF "$1 $2" "$WORK/supports"; }

# Resolve a yaml's deps to other local yamls it depends on.
# All lookups happen in one awk pass against $WORK/providers (busybox lacks `join`).
resolve_deps() {
    awk -v self="$1" -v deps="$2" '
        { p[$1] = p[$1] " " $2 }
        END {
            n = split(deps, d, ",")
            for (i = 1; i <= n; i++) {
                name = d[i]
                sub(/[~=<>!].*/, "", name)
                if (name == "" || !(name in p)) continue
                m = split(p[name], a, " ")
                for (j = 1; j <= m; j++)
                    if (a[j] != "" && a[j] != self) print a[j]
            }
        }
    ' "$WORK/providers" | sort -u
}

cat <<'YAML'
# Auto-generated by .gitlab/gen-dag.sh — do not edit.
stages: [build]

# IS_MAIN is set by the parent pipeline's `build` job rules:
#   "true"  → push to main: OUT_DIR=/apks (NFS, served by apks.sko.ai), sign
#             with prod key.
#   "false" → MR: OUT_DIR=$CI_PROJECT_DIR/packages (ephemeral, never served),
#             throwaway signing key.
# Both modes run `melange test` after build (on main, the apk is already in
# /apks by the time test runs, so a failed test surfaces a regression but
# doesn't prevent publication — fix-forward / revert in that case).
# Both modes share /apks/{melange,apks}-cache — caches are content-addressed
# so MR builds populate/reuse them without affecting prod served output.
# MELANGE_RSA is a protected CI variable, so it isn't injected on MRs even
# if the script tried to read it.
.build:
  stage: build
  image:
    name: ghcr.io/vaskozl/melange:0.50.4@sha256:fa3d4159ecf0402860fd768ed8dd9ba349e5623d4aab9138943d5fc00fd076ae
    entrypoint: [""]
  before_script:
    - |
      set -eu
      # Caches (/apks/{melange,apks}-cache) are content-addressed and safe to
      # share between main and MR jobs. Only OUT_DIR — where signed apks land
      # and become servable — must stay MR-private.
      export CACHE_DIR=/apks/melange-cache
      export APK_CACHE_DIR=/apks/apks-cache
      if [ "$IS_MAIN" = "true" ]; then
        echo "${MELANGE_RSA}" > melange.rsa
        # Derive and publish the matching public key so consumers always see
        # the key that matches the active signing key (self-heals on rotation).
        # Requires openssl in the melange image (apkontainers!750 — openssl-config).
        openssl rsa -in melange.rsa -pubout -out melange.rsa.pub
        if ! cmp -s melange.rsa.pub /apks/melange.rsa.pub; then
          cp melange.rsa.pub /apks/melange.rsa.pub
        fi
        export OUT_DIR=/apks
      else
        melange keygen melange.rsa
        export OUT_DIR=$CI_PROJECT_DIR/packages
      fi
      mkdir -p "$OUT_DIR" "$CACHE_DIR" "$APK_CACHE_DIR"
  variables:
    MELANGE_FLAGS: >-
      --workspace-dir=$CI_PROJECT_DIR
      --arch=$ARCH
      --runner=bubblewrap
      --repository-append=https://apks.sko.ai,https://packages.wolfi.dev/os
      --keyring-append=melange.rsa.pub,https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      --pipeline-dirs=./pipelines
      --env-file=common.env
  retry: 2
  script:
    - >-
      melange build "$PKG" $MELANGE_FLAGS
      --source-dir="${PKG%.yaml}"
      --out-dir="$OUT_DIR"
      --cache-dir="$CACHE_DIR"
      --apk-cache-dir="$APK_CACHE_DIR"
      --repository-append="$OUT_DIR"
      --signing-key=melange.rsa
    - >-
      melange test "$PKG" $MELANGE_FLAGS
      --source-dir="${PKG%.yaml}"
      --apk-cache-dir="$APK_CACHE_DIR"
      --repository-append="$OUT_DIR"
      --test-package-append=busybox
      --ignore-signatures
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - packages/

noop:
  stage: build
  image: busybox
  script: ["true"]
  rules:
    - if: $IS_MAIN == "true"
    - if: $IS_MAIN == "false"

YAML

while IFS='|' read -r base _ _ deps; do
    local_deps=$(resolve_deps "$base" "$deps")

    for arch in amd64 arm64; do
        arch_supported "$base" "$arch" || continue

        cat <<YAML
$base-$arch:
  extends: .build
  tags: [$arch]
  variables:
    PKG: $base.yaml
    ARCH: $arch
  rules:
    - if: \$IS_MAIN == "true"
      changes:
        - $base.yaml
        - $base/**/*
    - if: \$IS_MAIN == "false"
      changes:
        - $base.yaml
        - $base/**/*
    - when: never
YAML

        needs_header=
        for dep in $local_deps; do
            arch_supported "$dep" "$arch" || continue
            [ -z "$needs_header" ] && { printf '  needs:\n'; needs_header=1; }
            printf '    - {job: %s-%s, optional: true}\n' "$dep" "$arch"
        done
        echo
    done
done <"$WORK/rows"
